export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  UPDATE_FOLLOWINGS: 'UPDATE_FOLLOWINGS',

  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
};

export const postConstants = {
  GET_POSTS: 'GET_POSTS',
  GET_MY_POST: 'GET_MY_POST',

  GET_MYFOLLOWINGS_POST_REQUEST: 'GET_MYFOLLOWINGS_POST_REQUEST',
  GET_MYFOLLOWINGS_POST_SUCCESS: 'GET_MYFOLLOWINGS_POST_SUCCESS',

  CREATE_POST_REQUEST: 'CREATE_POST_REQUEST',
  CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
  CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',

  LIKE_POST: 'LIKE_POST',
  UNLIKE_POST: 'UNLIKE_POST',

  LIKE_POST_REQUEST: 'LIKE_POST_REQUEST',
  UNLIKE_POST_REQUEST: 'UNLIKE_POST_REQUEST',

  DELETE_COMMENT: 'DELETE_COMMENT',
  DELETE_COMMENT_REQUEST: 'DELETE_COMMENT_REQUEST',
};

export const userConstants = {
  GET_ALL_USERS: 'GET_ALL_USERS',

  GET_USER_PROFILE: 'GET_USER_PROFILE',
  GET_USER_INFO: 'GET_USER_INFO',
  GET_USER_PROFILE_REQUEST: 'GET_USER_PROFILE_REQUEST',
  GET_USER_PROFILE_FAILURE: 'GET_USER_PROFILE_FAILURE',

  GET_FOLLOWERS_DETAILS: 'GET_FOLLOWERS_DETAILS',
  GET_FOLLOWINGS_DETAILS: 'GET_FOLLOWINGS_DETAILS',

  FOLLOW_USER_REQUEST: 'FOLLOW_USER_REQUEST',
  FOLLOW_USER: 'FOLLOW_USER',

  UNFOLLOW_USER_REQUEST: 'UNFOLLOW_USER_USER',
  UNFOLLOW_USER: 'UNFOLLOW_USER',

  UPDATE_USER_DETAILS: 'UPDATE_USER_DETAILS',

  CLEAR_USER: 'CLEAR_USER',
};

export const conversationConstants = {
  GET_ALL_CONVERSATIONS: 'GET_ALL_CONVERSATIONS',

  NEW_CONVERSATION: 'NEW_CONVERSATION',

  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',

  POST_NEW_MESSAGE: 'POST_NEW_MESSAGE',

  PERSIST_CONVERSATION_ID: 'PERSIST_CONVERSATION_ID',

  GET_RECEIVER: 'GET_RECEIVER',

  DELETE_CONVERSATION: 'DELETE_CONVERSATION',
};
